- name: Generate certificate key
  openssl_privatekey:
    path: "{{ key_file }}"
    size: 2048
    type: RSA
    cipher: auto
    passphrase: ""
  become: true

- name: Generate certificate signing request
  openssl_csr:
    path: /tmp/example.csr
    privatekey_path: "{{ key_file }}"
    common_name: "{{ common_name }}"
    # privatekey_passphrase: ""
    key_usage:
      - digitalSignature
      - keyEncipherment
      - nonRepudiation
    extended_key_usage:
      - serverAuth
      
- name: Generate self-signed certificate
  openssl_certificate:
    path: "{{ cert_file }}"
    privatekey_path: "{{ key_file }}"
    # privatekey_passphrase: ""
    csr_path: /tmp/example.csr
    provider: selfsigned
