---
- name: Enable mariadb service first
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

- name: Setup MySQL
  mysql_user:
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_passwd }}'
    state: present

- name: create user
  command: mysql -u root -p"{{ mysql_root_passwd }}" -e "CREATE USER 'wiki'@'localhost' IDENTIFIED BY '{{ mysql_user_passwd }}';"

- name: create db
  command: mysql -u root -p"{{ mysql_root_passwd }}" -e "CREATE DATABASE wikidatabase;"

- name: grant priv
  command: mysql -u root -p"{{ mysql_root_passwd }}" -e "GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'localhost';"

- name: flush priv
  command: mysql -u root -p"{{ mysql_root_passwd}}" -e "FLUSH PRIVILEGES;"

