---
- name: Enable httpd service
  systemd:
    name: httpd.service
    enabled: yes
    state: started

- name: Enable mariadb service
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

# - name: Reboot the host
#   reboot:
#     reboot_timeout: 600
#     pre_reboot_delay: 0
#     post_reboot_delay: 30

# - name: Wait for host to come back up
#   wait_for_connection:
#     delay: 10
#     timeout: 300